version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres2024
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin2024
    ports:
      - "5050:80"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "4200:4200"

